export const ADMIN_ROUTES = {
  LOGIN: '/admin/login',
  DASHBOARD: '/admin/dashboard',
  USERS: '/admin/users',
  TESTS: '/admin/tests',
  PAYMENTS: '/admin/payments',
  ANALYTICS: '/admin/analytics',
  SETTINGS: '/admin/settings',
  QUESTIONS: '/admin/questions',
  COUPONS: '/admin/coupons',
  NOTIFICATIONS: '/admin/notifications',
  TICKETS: '/admin/tickets',
  BANNERS: '/admin/banners',
  FAQS: '/admin/faqs',
  ANNOUNCEMENTS: '/admin/announcements',
  BATCHES: '/admin/batches',
  ACTIVITY_LOGS: '/admin/activity-logs',
  REPORTS: '/admin/reports',
  STUDY_MATERIALS: '/admin/study-materials',
} as const;

export const ADMIN_API_ENDPOINTS = {
  AUTH: '/auth/admin-login',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  TESTS: '/tests',
  PAYMENTS: '/payments',
  ANALYTICS: '/analytics',
  SETTINGS: '/settings',
  QUESTIONS: '/questions',
  COUPONS: '/coupons',
  NOTIFICATIONS: '/notifications',
  TICKETS: '/tickets',
  BANNERS: '/banners',
  FAQS: '/faqs',
  ANNOUNCEMENTS: '/announcements',
  BATCHES: '/batches',
  GROUPS: '/groups',
  ACTIVITY_LOGS: '/activity-logs',
  RESULTS: '/results',
  REPORTS: '/reports',
  STUDY_SUBJECTS: '/study/subjects',
  STUDY_MATERIALS: '/study/materials',
} as const;
